version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    user: root
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "rootRoot123@"
    ports:
      - 1433:1433
    volumes:
      - ~/my-volume/opt/mssql:/var/opt/mssql
      - ~/my-volume/opt/sqlserver:/var/opt/sqlserver
volumes:
  my-volume: